### ISSUE TITLE
How is it different from Nats.io

### ISSUE THREAD

**Issue by lonnietc** [matrix-org/pinecone#40]
Hello,

I am trying to get a feel for Pinecone and its capabilities and have read about the comparisons that you made with Yggdrasil and LibP2P but am trying to determine how it also compares to Nats.io in that this also seems to be similar and for scaling out to thousands of P2P nodes.

I am working towards some P2P projects and was actually initially considering Yggdrasil and LibP2P, but if Pinecone and/or Nats.io are better choices then I want to look into them as well.

Actually, I like what I have read about Pinecone and also do not mind if the project is cutting-edge since the P2P projects  that I have in mind are also going to be cutting-edge and I expect a bit of development and evolution to happen.

thanks

**Comment by neilalexander** [comment]
Pinecone, Yggdrasil and libp2p are more intended for point-to-point networking between untrustworthy nodes, whereas NATS is more of a generic message bus in a trusted environment. I suspect there are odd places the functionality may overlap (like you could send point-to-point messages over NATS) but otherwise they are not that similar.

**Comment by lonnietc** [comment]
Thanks for the clarification on this, my friend.
